FROM node:16-alpine
WORKDIR /ProjectIdeagpt/
COPY public/ /ProjectIdeagpt/public
COPY src/ /ProjectIdeagpt/src
COPY package.json /ProjectIdeagpt/
COPY index.html /ProjectIdeagpt/
RUN npm install
CMD ["npm", "start"]